name: oracle
version: 0.1.0
description: >
  Dart library for Oracle database access.
authors:
- Michael Loveridge <loveridge.michael@gmail.com>
- Chris Lucas <chris@chrisjlucas.com>
- Austin Cummings <austin@austincummings.com>
homepage: https://github.com/oracle-dart/oracle.dart
environment:
#  sdk: ">=1.8.0 <2.0.0"
  sdk: ">2.0.0"
dependencies:
  grinder: ^0.9.0
dev_dependencies:
  logging: ^0.11.4
#  test: ^1.20.2
#  dart_coveralls: ^0.6.0+4
